### ISSUE TITLE
GIF files get stuck on first frame

### ISSUE THREAD

**Issue by kineticneticat** [brandon3055/PI-Docs#26]
Hi!

I tried adding a .gif file to a page, but it only shows the first frame.
The image is hosted at https://i.ibb.co/bdw9szC/logo.gif and is definitely a .gif with more just than the first frame.
It is also not just limited to this .gif as I tested with a couple of others and have had the same problem.

**Comment by FoxMcloud5655** [comment]
Interesting, but please post this on Project intelligence, not on PI Docs.

**Comment by kineticneticat** [comment]
ok!
