### ISSUE TITLE
Enigmatica 2 Expert, files not downloading

### ISSUE THREAD

**Issue by MountEverfresh2** [brandon3055/PI-Docs#27]
When I try and use PI it tells me "Failed to download the PI mod manifest"

Is there a way I can just manually use the files here with no download?

**Comment by FoxMcloud5655** [comment]
Yes, you can.  Download this repository, then in PI, turn on edit mode and point it to the extracted files from the repository.

**Comment by MountEverfresh2** [comment]
That worked, thank you!
